"""utils.py - Utility helpers for LGD Fuzzy Matcher."""
import json, logging, re
from pathlib import Path
from typing import Any
import pandas as pd


def load_config(config_path: str = "config.json") -> dict:
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def setup_logging(log_file: str = "lgd_matcher.log", level: str = "INFO") -> logging.Logger:
    logger = logging.getLogger("lgd_matcher")
    if logger.handlers:
        return logger
    logger.setLevel(getattr(logging, level.upper(), logging.INFO))
    fmt = logging.Formatter("%(asctime)s | %(levelname)-8s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
    for h in [logging.StreamHandler(), logging.FileHandler(log_file, encoding="utf-8")]:
        h.setFormatter(fmt)
        logger.addHandler(h)
    return logger


def is_blank(value: Any) -> bool:
    if value is None:
        return True
    if isinstance(value, float) and pd.isna(value):
        return True
    return str(value).strip() == ""


def normalize_text(text: Any, stop_words: list = None) -> str:
    if is_blank(text):
        return ""
    t = str(text).strip().lower()
    t = t.replace("&", " and ")
    t = re.sub(r"[^a-z0-9\s]", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    if stop_words:
        sw = [re.escape(str(w).strip().lower()) for w in stop_words if str(w).strip()]
        if sw:
            t = re.sub(r"\b(" + "|".join(sw) + r")\b", " ", t)
    return re.sub(r"\s+", " ", t).strip()


def normalize_alias_map(alias_map: dict, stop_words: list) -> dict:
    return {normalize_text(k, stop_words): v for k, v in alias_map.items() if normalize_text(k, stop_words)}


def save_matched_csv(df: pd.DataFrame, output_path: str) -> None:
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False, encoding="utf-8-sig")


def save_unmatched_csv(df: pd.DataFrame, output_path: str) -> None:
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    df[df["match_status"] == "NOT_FOUND"].to_csv(output_path, index=False, encoding="utf-8-sig")


def generate_sql_update(df: pd.DataFrame, table_name: str = "target_table", output_path: str = "lgd_updates.sql") -> None:
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    matched = df[df["match_status"] != "NOT_FOUND"]
    lines = [f"-- Auto-generated by LGD Fuzzy Matcher\n-- Total updates: {len(matched)}\n"]
    for _, row in matched.iterrows():
        sc = "NULL" if is_blank(row["state_lgd_code"]) else int(float(row["state_lgd_code"]))
        dc = "NULL" if is_blank(row["district_lgd_code"]) else int(float(row["district_lgd_code"]))
        lines.append(
            f"UPDATE {table_name}\nSET state_lgd_code = {sc},\n    district_lgd_code = {dc}\nWHERE id = {repr(row['id'])};\n"
        )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
